name: Daily Post Generator

on:
  schedule:
    - cron: '35 18 * * *'  # Runs daily at 00:05 IST (18:35 UTC)
  workflow_dispatch:      # Allows manual triggering for testing

jobs:
  generate-post:
    runs-on: ubuntu-latest
    steps:
      - name: Call Distribute Holiday Post API
        run: |
          curl -X POST http://3.15.138.191:8001/subscriber/distribute -H "Content-Type: application/json"
