name: Daily Post Generator

on:
  schedule:
    - cron: "30 6 * * *" # Runs daily at 12:00 PM IST (06:30 UTC)
  workflow_dispatch:

jobs:
  generate-post:
    runs-on: ubuntu-latest
    steps:
      - name: Call Distribute Holiday Post API
        run: |
          curl -X POST http://3.15.138.191:8001/subscriber/distribute -H "Content-Type: application/json"
